#!/bin/sh
### BEGIN INIT INFO
# Provides:          reth-sync
# Required-Start:    $network $remote_fs fetch-config
# Required-Stop:     $network $remote_fs
# Default-Start:     5
# Default-Stop:      0 1 6
# Short-Description: Sync data using rclone
# Description:       Runs rclone sync script to synchronize data from R2 storage
### END INIT INFO

start() {
    echo "This is local dev, reth-sync snapshot is disabled!"
}

case "$1" in
    start)
        start
        ;;
    *)
        echo "Usage: $0 start" >&2
        exit 1
        ;;
esac

exit 0
